### ISSUE TITLE
Untangle QGCSend

### ISSUE THREAD

**Issue by josephlewis42** [josephlewis42/autopilot#50]
QGCLink currently uses lots of signals to get data, these should use the new API in driver.

**Comment by ghost** [comment]
All of the driver-based messages have been pulled into their individual drivers, using the new API. The only things remaining in QGCSend are the heartbeat, and the "UAlberta System Status" message. The heartbeat can probably remain in QGCSend, the system status could also remain but should be hooked into SystemState so that we can remove all the signal bindings (which are only used to redundantly store values in QGCSend).
